---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
- name: ubuntu-10.04
- name: centos-6.4
- name: centos-5.9
- name: amazon-2014.09.1
  driver:
    name: ec2
    region: us-east-1
    image_id: ami-b66ed3de
    flavor_id: m3.medium
    ebs_volume_size: 8
    ebs_delete_on_termination: true
    ebs_device_name: /dev/sda
    username: ec2-user

suites:
- name: default
  run_list: ["recipe[minitest-handler]", "recipe[timezone-ii]"]
  attributes: {}
